version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9  # Base CircleCI executor
    working_directory: ~/app

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Pull latest code from GitHub
      - setup_remote_docker  # Enable Docker in CircleCI
      - run:
          name: Build Docker Image
          command: docker build -t mydockerhubusername/my-image:latest .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push mydockerhubusername/my-image:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: main
            paths:
              only:
                - src/*
                - docker/*
